// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Product_Count_Category : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Product_Count_Category));
        
        string IMigrationMetadata.Id
        {
            get { return "202106071502286_Product_Count_Category"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
